version: "3.8"

networks:
  default:
    external: true
    name: ergo-node

volumes:
  ergo_node:
    external: true

services:
  # Ergo blockchain node
  node:
    image: ergoplatform/ergo:v4.0.23
    command: --mainnet -c /etc/ergo.conf
    volumes:
      - ergo_node:/home/ergo/.ergo
      - ./ergo.conf:/etc/ergo.conf:ro
    ports:
      - "9053:9053"
      - "9030:9030"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
